spring:
  thymeleaf:
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photostudio?useUnicode=true&characterEncoding=utf8
    username: root
    password: zhouyiran
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.photo.parentPath}
  servlet:
    multipart:
      max-file-size: 100Mb
upload:
  photo:
    parentPath: D:\photos\
    path: D:\photos\photo\